### ISSUE TITLE
Script starts and then stops immediately 

### ISSUE THREAD

**Issue by wcktklwn** [sealemar/BingRewards#106]
I recently moved my script to a new computer and it fails to run. I verified that I am using the latest version.

% python2 main.py --version
Bing! Rewards Automation script: <http://sealemar.blogspot.com/2012/12/bing-rewards-automation.html>
Version: 3.8.3 from January 05, 2015
See 'version.txt' for the list of changes
This code is published under LGPL v3 <http://www.gnu.org/licenses/lgpl-3.0.html>
There is NO WARRANTY, to the extent permitted by law.

Developed by: Sergey Markelov

When I removed the events section of the config, I receive the following traceback.

% python2 /opt/bingrewards/bin/main.py -f /opt/bingrewards/bin/config.xml
2015-01-15 10:04:10.0 - script started
--------------------------------------------------------------------------------

For: Live - email@address.com

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/bingrewards/bin/main.py", line 294, in <module>
    EventsProcessor.onScriptFailure(config, e)
  File "/opt/bingrewards/bin/main.py", line 292, in <module>
    __run(config)
  File "/opt/bingrewards/bin/main.py", line 217, in __run
    reportItem = __processAccountUserAgent(config, account, bingCommon.USER_AGENTS_PC, doSleep)
  File "/opt/bingrewards/bin/main.py", line 204, in __processAccountUserAgent
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "/opt/bingrewards/bin/main.py", line 177, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "/opt/bingrewards/bin/main.py", line 54, in earnRewards
    rewards = bfp.parseFlyoutPage(bingRewards.requestFlyoutPage(), bingCommon.BING_URL)
  File "/opt/bingrewards/bin/pkg/bingFlyoutParser.py", line 104, in parseFlyoutPage
    parser.feed(page[s:e])
  File "/usr/lib/python2.7/HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "/usr/lib/python2.7/HTMLParser.py", line 155, in goahead
    if i < j: self.handle_data(rawdata[i:j])
  File "/opt/bingrewards/bin/pkg/bingFlyoutParser.py", line 234, in handle_data
    self.reward.progressMax = int(progress[1])
ValueError: invalid literal for int() with base 10: '1 credit'

I suspect I am missing a python library, but I am unable to figure out what library is needed.

**Comment by goostoff** [comment]
See #104 for the code edit for resolution.  It worked for me.

**Comment by wcktklwn** [comment]
Issue #104 resolved the issue.
