### ISSUE TITLE
Bing-automation script crashes

### ISSUE THREAD

**Issue by hakanaikioku** [sealemar/BingRewards#109]
I have tried the troubleshooting guide and here is what I get:
script version: 3.8.6
I downloaded it today 26 Jan 2015 using the download zip link on the github page.
Python version: 2.7.2
OS: Windows
The script crashes with a "substring not found" value error when I run it.

Command line and script output follow:

D:\projects\bing\BingRewards-master>c:\Python27\python main.py
2015-01-27 04:16:25.8 - script started
--------------------------------------------------------------------------------

For: Live - kilrathisaga215e1a8@hotmail.com

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "main.py", line 295, in <module>
    EventsProcessor.onScriptFailure(config, e)
  File "main.py", line 293, in <module>
    __run(config)
  File "main.py", line 218, in __run
    reportItem = __processAccountUserAgent(config, account, bingCommon.USER_AGENTS_PC, doSleep)
  File "main.py", line 205, in __processAccountUserAgent
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "main.py", line 178, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "main.py", line 52, in earnRewards
    bingAuth.authenticate(reportItem.accountType, reportItem.accountLogin, password)
  File "pkg\bingAuth.py", line 289, in authenticate
    authMethod(login, password)
  File "pkg\bingAuth.py", line 242, in __authenticateLive
    s = page.index("<form ")
ValueError: substring not found

**Comment by hakanaikioku** [comment]
sorry I got a non visible character in my password somehow. corrected and fixed.
