### ISSUE TITLE
Element tree parse error

### ISSUE THREAD

**Issue by jewjitsu012** [sealemar/BingRewards#110]
Getting this issue on OSX Python 2.7

Traceback (most recent call last):
  File "main.py", line 284, in <module>
    config.parseFromFile(configFile)
  File "pkg/config.py", line 487, in parseFromFile
    tree = et.parse(configFile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 19, column 22

**Comment by sealemar** [comment]
have you confirmed that your ```config.xml``` is correctly formatted?

**Comment by sealemar** [comment]
closing due to no activity

**Comment by ds1239** [comment]
Hello? I am getting the same issue.

**Comment by ds1239** [comment]
My error is the first line of the first account in the events section

**Comment by PlasmaPower** [comment]
@ds1239 Could you please post your config with your email and password censored? It is most likely a config error.

**Comment by ds1239** [comment]
<?xml version="1.0"?>
<configuration>
    <general
    betweenQueriesInterval="4.0"
    betweenQueriesSalt="3.0"
    betweenAccountsInterval="100"
    betweenAccountsSalt="200"
    openTopLinkRange="3"
    openLinkChance=".2"
    addSearchesDesktop="30"
    addSearchesDesktopSalt="5"
    addSearchesMobile="20"
    addSearchesMobileSalt="5" />
    
    
    <accounts>
        <account type="Live" disabled="false">
            <login>ds1244@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>dsmith1241@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>dsmith1243@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>dsmith1243@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>dsmith1246@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>dsmith1248@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>eekdmfzd@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>fcrmfsrn@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>gtrckxuf@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>mrsmith234@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>qathmhmt@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>umrzwbtz@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>FriedaLJohnsonds@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>MavisWMcGladedms@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>dsMatthewTAnderson@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>JamesAHarms@outlook.com</login>
            <password>xxxxxx</password>
        </account>
    </accounts>
    <events>
        <onError>
            <retry interval="15" salt="13.5" count="3" />
            <notify cmd="/home/BingRewards/bin/BingRewards/notify/onError.sh %a %p %r %P %l %i %e" />
        </onError>
        <onComplete>
            <retry if="%p lt 16" interval="15" salt="13.5" count="3" />
            <notify if="%l gt 3000"
            cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
            <notify if="%p ne 16"
            cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
            <notify if="%P gt 475"
            cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
            <account ref="Live_ds1244@outlook.com">
                <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                <notify if="%l gt 10000"
cmd=‘/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31"
                    cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475"
                    cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_dsmith1241@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000"
                    cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31"
                    cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475"
                    cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_dsmith1243@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000"
                    cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31"
                    cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475"
                    cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_dsmith1246@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_dsmith1248@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_eekdmfzd@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_fcrmfsrn@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_gtrckxuf@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_mrsmith234@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_qathmhmt@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_umrzwbtz@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_FriedaLJohnsonds@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_MavisWMcGladedms@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_dsMatthewTAnderson@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    </onComplete>
                    <onScriptComplete>
                    <notify cmd="/BingRewards/notify/onScriptComplete.sh -mail" />
                    </onScriptComplete>
                    <onScriptFailure>
                    <notify cmd="/BingRewards/notify/onScriptFailure.sh -mail" />
                    </onScriptFailure>
                    </events>
                    
                    <queries generator="wikipedia" />
                </configuration>

**Comment by amayer5125** [comment]
@ds1239 something like:
\`\`\`xml
config here
 \`\`\`

**Comment by ds1239** [comment]
```
<?xml version="1.0"?>
<configuration>
    <general
    betweenQueriesInterval="4.0"
    betweenQueriesSalt="3.0"
    betweenAccountsInterval="100"
    betweenAccountsSalt="200"
    openTopLinkRange="3"
    openLinkChance=".2"
    addSearchesDesktop="30"
    addSearchesDesktopSalt="5"
    addSearchesMobile="20"
    addSearchesMobileSalt="5" />
    <!--
     openTopLinkRange looks at the top X results, and randomly clicks one
     openLinkChance is the chance that a Bing result will be opened
     Lower the addSearches values if you have three or more accounts
     If you have one account, an average of 30 extra searches a day is fine
     If you have 5 accounts, an average of 150 extra searches a day is probably not good
     -->
    <!--
     - Note: login and password are optional
     -       if not set, the proxy is considered open
     -       only Basic HTTP Authentication is currently supported
     -       protocols: a comma separated list of values - i.e, "http,https"
     <proxy protocols="http,https" url="218.204.159.45:8123" login="John Smith" password="xxx" />
     -->
    <accounts>
        <account type="Live" disabled="false">
            <login>ds1244@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>dsmith1241@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>dsmith1243@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>dsmith1243@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>dsmith1246@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>dsmith1248@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>eekdmfzd@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>fcrmfsrn@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>gtrckxuf@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>mrsmith234@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>qathmhmt@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>umrzwbtz@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>FriedaLJohnsonds@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>MavisWMcGladedms@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>dsMatthewTAnderson@outlook.com</login>
            <password>xxxxxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>JamesAHarms@outlook.com</login>
            <password>xxxxxx</password>
        </account>
    </accounts>
    <events>
        <onError>
            <retry interval="15" salt="13.5" count="3" />
            <notify cmd="/home/BingRewards/bin/BingRewards/notify/onError.sh %a %p %r %P %l %i %e" />
        </onError>
        <onComplete>
            <retry if="%p lt 16" interval="15" salt="13.5" count="3" />
            <notify if="%l gt 3000"
            cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
            <notify if="%p ne 16"
            cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
            <notify if="%P gt 475"
            cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
            <account ref="Live_ds1244@outlook.com">
                <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                <notify if="%l gt 10000"
cmd=‘/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31"
                    cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475"
                    cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_dsmith1241@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000"
                    cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31"
                    cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475"
                    cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_dsmith1243@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000"
                    cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31"
                    cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475"
                    cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_dsmith1246@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_dsmith1248@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_eekdmfzd@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_fcrmfsrn@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_gtrckxuf@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_mrsmith234@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_qathmhmt@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_umrzwbtz@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_FriedaLJohnsonds@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_MavisWMcGladedms@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    <account ref="Live_dsMatthewTAnderson@outlook.com">
                    <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                    <notify if="%l gt 10000" cmd='/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                    <notify if="%p ne 31" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    <notify if="%P gt 475" cmd="/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                    </account>
                    </onComplete>
                    <onScriptComplete>
                    <notify cmd="/BingRewards/notify/onScriptComplete.sh -mail" />
                    </onScriptComplete>
                    <onScriptFailure>
                    <notify cmd="/BingRewards/notify/onScriptFailure.sh -mail" />
                    </onScriptFailure>
                    </events>
                    <!--
                    - generator="MODULE" must be a module in pkg/queryGenerators
                    - current modules:
                    -     bing - uses today's bing news page. Generates terms which may be partial words.
                    -     wikipedia - uses today's wikipedia. Generates terms with whole words.
                    -     googleTrends - uses today's google trends, and google suggested searches. This generatoer
                    -	                   generates whole words, generally consistent with a search syntax.  These terms
                    -                    are anything trending and can be NSFW or terms for illegal items.
                    -->
                    <queries generator="wikipedia" />
                </configuration>
```

**Comment by ds1239** [comment]
Here is the Error:
```
2015-07-09 12:56:20.5 - script started
--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "main.py", line 293, in <module>
    config.parseFromFile(configFile)
  File "pkg/config.py", line 519, in parseFromFile
    tree = et.parse(configFile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1183, in parse
    tree.parse(source, parser)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 110, column 4

```

**Comment by amayer5125** [comment]
on line 110 `<notify if="%l gt 10000"
cmd=‘/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />` you have a weird single quote after `cmd=` can you make it a regular single quote and try again?

**Comment by ds1239** [comment]
I changed it to a normal single quote, and it works! Thanks! One more thing: How many searches does the program do if I have     
    addSearchesDesktop="0"
    addSearchesDesktopSalt="0"
    addSearchesMobile="0"
    addSearchesMobileSalt="0"?

**Comment by amayer5125** [comment]
it will do the bear minimum. so 30 desktop and 20 mobile

**Comment by amayer5125** [comment]
@ds1239 I noticed you have quite a few accounts in your config file. I believe Bing! marks anything over 5 or 6 accounts coming from 1 ip address as being a bot. I would use caution when using this many accounts.

**Comment by ds1239** [comment]
Thanks for the heads up. Am I able to set up some sort of dynamic ip to throw them off?

**Comment by ds1239** [comment]
I have DHCP set up. Would that work?

**Comment by PlasmaPower** [comment]
@ds1239 DHCP is a local dynamic IP. Bing only sees your global IP. You'll need some sort of proxy.

**Comment by ds1239** [comment]
How could I set that up?

**Comment by PlasmaPower** [comment]
Currently, this script doesn't have support for proxies, so you simply proxy all the accounts through a proxy, or none. As for proxying all connections, look [here](https://superuser.com/questions/410142/how-to-route-traffic-through-a-specific-socks-proxy-on-a-per-app-basis).

**Comment by sealemar** [comment]
@ds1239 as @amayer5125 has already said, Bing! most likely will ban you if you're trying to spam it with too many accounts. What number is considered to be ```too many``` is not for us to decide and I wouldn't even speculate about it.

An ideal world would be to have a script which registers unlimited number of accounts for you automatically, distributes accounts randomly between some randomly ranged set of externally facing IPs, bings for you automatically and then automatically gathers the yield from Bing! on every account, logs in to your Amazon account (as an example) and activates all gift cards which have been just earned for you.

Unfortunately, we are in a real world and we don't have unlimited supply of external IPs.

**Comment by ds1239** [comment]
I'm pretty sure this can be done. One could edit this script to configure a public proxy to do the searches on, and have a different proxy for every ~3 accounts. Have the script detect when the account has enough points to get an amazon code, and then have the script either 1. redeem the points for you and print the amazon code in the final report or 2. simply notify you the account and proxy used so you could do it manually. So far, the only functionality I added to the script is I had it text me whenever an account has more than 525 points. It's not perfect yet, but it works.

**Comment by ds1239** [comment]
- http://stackoverflow.com/questions/5620263/using-an-http-proxy-python -How to connect ot proxy
- many sites for sms verification
- http://www.fakenamegenerator.com/ - make accounts based on this

**Comment by sealemar** [comment]
@ds1239 anything can be implemented, but you may find implementing all of that quiet time consuming. If someone would like to invest his/her time and make a contribution, I'm sure all ```BingRewards``` customers will welcome that.
