### ISSUE TITLE
script crash right in middle of getting points

### ISSUE THREAD

**Issue by iceberg1369** [sealemar/BingRewards#119]
I sometimes got folowing error.
2015-02-14 22:01:04.8 - 15/30 - Search: John Ehrlichman
2015-02-14 22:01:06.2 - 16/30 - Search: Henri Laurent
2015-02-14 22:01:07.5 - 17/30 - Search: Dora Gerson
2015-02-14 22:01:09.0 - 18/30 - Search: Rob Thomas
2015-02-14 22:01:10.8 - 19/30 - Search: Yusuf Salman Yusuf
2015-02-14 22:01:12.4 - 20/30 - Search: Vincent Crane
2015-02-14 22:01:13.9 - 21/30 - Search: Liv Kristine

For: Live - maria.howard***@outlook.com

--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\BingRewards\main.py", line 299, in <modul
e>
    EventsProcessor.onScriptFailure(config, e)
  File "C:\Users\Administrator\Desktop\BingRewards\main.py", line 297, in <modul
e>
    __run(config)
  File "C:\Users\Administrator\Desktop\BingRewards\main.py", line 222, in __run
    reportItem = __processAccountUserAgent(config, account, bingCommon.USER_AGEN
TS_PC, doSleep)
  File "C:\Users\Administrator\Desktop\BingRewards\main.py", line 209, in __proc
essAccountUserAgent
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "C:\Users\Administrator\Desktop\BingRewards\main.py", line 182, in __proc
essAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "C:\Users\Administrator\Desktop\BingRewards\main.py", line 59, in earnRew
ards
    results = bingRewards.process(rewards)
  File "C:\Users\Administrator\Desktop\BingRewards\pkg\bingRewards.py", line 344
, in process
    res = self.__processSearch(r)
  File "C:\Users\Administrator\Desktop\BingRewards\pkg\bingRewards.py", line 296
, in __processSearch
    page = helpers.getResponseBody(response)
  File "C:\Users\Administrator\Desktop\BingRewards\pkg\helpers.py", line 64, in
getResponseBody
    try:     content = data.read()
  File "C:\Python27\lib\gzip.py", line 249, in read
    self._read(readsize)
  File "C:\Python27\lib\gzip.py", line 303, in _read
    self._read_eof()
  File "C:\Python27\lib\gzip.py", line 342, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0xffdff != 0xa225cd68L

C:\Users\Administrator\Desktop\BingRewards>

**Comment by PlasmaPower** [comment]
> IOError: CRC check failed 0xffdff != 0xa225cd68L
Is your hard drive fine? I would think not.

**Comment by iceberg1369** [comment]
I use VPS, I have no issue with other applications. I can say my hard drive is functioning fine for sure.

**Comment by PlasmaPower** [comment]
That's odd. It's failing to make or read a gzip file it looks like.

**Comment by iceberg1369** [comment]
how can i restart script or retry when I face errors like this?

**Comment by PlasmaPower** [comment]
You can just run the script again.

**Comment by iceberg1369** [comment]
is there a way to automatically restart script when I face unknown crashes?

**Comment by TunaLobster** [comment]
Yes. I would take shell scripting, but it is possible. The computer only
knows when it starts and when it stops. You have to let it know if the
script ran properly or not.

This script is only as smart as we make it.
