### ISSUE TITLE
throwing an error out of nowhere

### ISSUE THREAD

**Issue by feedmewifi** [sealemar/BingRewards#176]
So I started my rewards thing and it threw the following error: 
```
C:\Users\Helmut\Desktop>python C:\Users\Helmut\Documents\BingRewards-master\main
.py
2015-12-02 16:01:35.8 - script started
--------------------------------------------------------------------------------



For: Live - [email]@gmail.com

--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\Helmut\Documents\BingRewards-master\main.py", line 300, in <mod
ule>
    EventsProcessor.onScriptFailure(config, e)
  File "C:\Users\Helmut\Documents\BingRewards-master\main.py", line 298, in <mod
ule>
    __run(config)
  File "C:\Users\Helmut\Documents\BingRewards-master\main.py", line 223, in __ru
n
    reportItem = __processAccountUserAgent(config, account, bingCommon.USER_AGEN
TS_PC, doSleep)
  File "C:\Users\Helmut\Documents\BingRewards-master\main.py", line 210, in __pr
ocessAccountUserAgent
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "C:\Users\Helmut\Documents\BingRewards-master\main.py", line 183, in __pr
ocessAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "C:\Users\Helmut\Documents\BingRewards-master\main.py", line 53, in earnR
ewards
    bingAuth.authenticate(reportItem.accountType, reportItem.accountLogin, passw
ord)
  File "C:\Users\Helmut\Documents\BingRewards-master\pkg\bingAuth.py", line 289,
 in authenticate
    authMethod(login, password)
  File "C:\Users\Helmut\Documents\BingRewards-master\pkg\bingAuth.py", line 183,
 in __authenticateLive
    s = page.index(ppsxParam)
ValueError: substring not found

C:\Users\Helmut\Desktop>pause
Press any key to continue . . .
```
So then I download the newest version and put my information into the config and ran it and I got this:
```

Traceback (most recent call last):
  File "main.py", line 293, in <module>
    config.parseFromFile(configFile)
  File "pkg\config.py", line 519, in parseFromFile
    tree = et.parse(configFile)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 48, column 6

C:\Users\Helmut\Desktop\BingRewards-master>
```
what should I do?? I'd like to get back to earning rewards soon becuase I was getting pretty close to a reward I was looking forward too. Thanks for the help!

**Comment by PlasmaPower** [comment]
This will be fixed by #175, please wait a bit for it to get merged.

**Comment by feedmewifi** [comment]
What does that mean and how will I know when it happens?

**Comment by PlasmaPower** [comment]
It just got merged, meaning the change got accepted, try updating to the latest version where should be fixed.

**Comment by iAmWillX** [comment]
The previous error is fixed however this is now occurring for me.

Here's an reference to the error...
```
Traceback (most recent call last):
  File "main.py", line 293, in <module>
    config.parseFromFile(configFile)
  File "pkg/config.py", line 519, in parseFromFile
    tree = et.parse(configFile)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 36, column 3
```

Thank you for the help.

**Comment by iAmWillX** [comment]
The latest merge isn't working for me. Receiving a log with nothing inside.

**Comment by Vixine** [comment]
I'm getting the same error
```python
2015-12-07 13:30:06.9 - script started
--------------------------------------------------------------------------------


Traceback (most recent call last):
  File "main.py", line 293, in <module>
    config.parseFromFile(configFile)
  File "pkg\config.py", line 519, in parseFromFile
    tree = et.parse(configFile)
  File "C:\tools\python2\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\tools\python2\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "C:\tools\python2\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\tools\python2\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 82, column 10
```

Thank you so much for supporting this!
Let me know if there's anything I can do to help.

**Comment by amayer5125** [comment]
That looks like there is something wrong with your config. Did you change anything in there?

**Comment by Vixine** [comment]
Wow, you're right, I can't believe I didn't just read the error report... (it even gives the line that had the error...) I'd commented out most of the events stuff but somehow missed a closing tag. Thanks.

**Comment by feedmewifi** [comment]
Alright so I fixed it by downloading a new version and putting in all my accounts by hand, so overall I don't really know what I did wrong. Thank you all for all your help!
