### ISSUE TITLE
Script crashing on links

### ISSUE THREAD

**Issue by uruloki** [sealemar/BingRewards#207]
I have 3 accounts, but the script crashes when it is trying to do the clicks on the first account. I can run the script again with that account disabled, it'll get through the second account and then crash on the links again. Right now I have to enable/disable each account to let the account run.

I am going to attempt disabling the code for clicking on the rewards links and see if it runs through all through the accounts.

**Comment by wipedout** [comment]
Similar experience, with multiple accts. Each will run if the others are disabled.
Are there elements at or near bingRewards.py", line 131 that should be changed or, for now, commented out?

Traceback (most recent call last):
  File "./main.py", line 304, in <module>
    EventsProcessor.onScriptFailure(config, e)
  File "./main.py", line 302, in <module>
    __run(config)
  File "./main.py", line 227, in __run
    reportItem = __processAccountUserAgent(config, account, bingCommon.USER_AGENTS_PC, doSleep)
  File "./main.py", line 214, in __processAccountUserAgent
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "./main.py", line 183, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "./main.py", line 70, in earnRewards
    reportItem.lifetimeCredits = bingRewards.getLifetimeCredits()
  File "./pkg/bingRewards.py", line 131, in getLifetimeCredits
    s = page.index("NAP")
ValueError: substring not found

**Comment by aidenator** [comment]
What I did for now is put a try/except around the offending line (pkg/bingRewards.py:131).

```
try:    
    s = page.index("NAP")
except:
    return 0
```

**Comment by specu** [comment]
why not
return -1
to indicate a problem?

**Comment by jamesalmeida** [comment]
I'm getting ```The server couldn't fulfill the request. Error code:  400``` every time I try to run mine now :(

**Comment by duddles** [comment]
Same for me with error code 400
