### ISSUE TITLE
AuthenticationError

### ISSUE THREAD

**Issue by zengfu94** [sealemar/BingRewards#262]
I've been facing this "AuthenticationError: Could not find variable t on Live login page", its started all of the sudden, I will do more testing with user agents. Just wondering if anyone else is getting this?

**Comment by codingqt** [comment]
Yup, getting the exact error starting today.

**Comment by zengfu94** [comment]
@codingqt I think MS is changing stuff.

**Comment by specu** [comment]
mine ran fine, I am getting lifetime total -1 though (not that i care)

**Comment by kenneyhe** [comment]
same here. does not seem adversely affect anything..

**Comment by rthomp10** [comment]
Having the same issue for all accounts. It used to be just one.

**Comment by rthomp10** [comment]
I logged into a few of the accounts and re-cloned the folder and found that the issue went away... I'm not sure why this is.

**Comment by DARKKRAKEN** [comment]
Any definitive way to fix this? Yesterday the script would run the searches but i would not get credit for the searches today it won't even log in it seems.

**Comment by chuybregts** [comment]
Try logging into the account from a browser.  I was prompted with a "confirm your backup email" prompt.  As soon as I went through that, the script worked again.

**Comment by Mailman74** [comment]
I have never seen this "confirm your backup email" once in the years I have been doing this

**Comment by adambird79** [comment]
Started getting this today also, tried logging into the accounts manually, and changing user agents still get the error.

**Comment by fraser1974** [comment]
I'm having the same problem. I tried cloning the folder again along with logging into the accounts to no avail.

**Comment by someuserx** [comment]
I ran into this issue today and it wouldn't let me continue. Went in and just commented out

bingAuth.py: 184-186, 228

`#        if ppsxSearch == None:`
`#            raise AuthenticationError("Could not find variable 't' on Live login page")`
`#        PPSX = ppsxSearch.group(1)`
`            #"PPSX"          : str(PPSX),`

Searches ran fine.

**Comment by abhidotnet** [comment]
@someuserx  I tried to do the exact same thing, but it is not working for me. My searches are still broken. I am guessing that MS has changed something on their end.

**Comment by someuserx** [comment]
@abhidotnet insert a `print page` statement in bingAuth after line 182: `ppsxSearch = self.ppsxValue.search(page)` and see what page bingAuth is trying to parse. This could give hints at to what to expect and adapt to.

**Comment by zengfu94** [comment]
@someuserx I've looked at it quite a bit and sometimes the t:/PPSX variable is not added to the page therefore I've just changed the lines to the following:
PPSXs = ["P","Pa","Pas","Pass","Passp","Passpo","Passpor","Passport","PassportR","PassportRN"]
PPSX = random.choice(PPSXs)

**Comment by DARKKRAKEN** [comment]
For a layman zengfu94 what did you chance to what?

**Comment by zengfu94** [comment]
@DARKKRAKEN 
In bingAuth.py remove lines 181-185 and replace them with mine above. Make sure to indent properly with spaces

**Comment by aaronjohnleonard** [comment]
@zengfu94 I still get "The server couldn't fulfill the request" when I replace those lines.

**Comment by DARKKRAKEN** [comment]
Worked a treat Zenfu94, thanks for your help!

**Comment by zengfu94** [comment]
@aaronjohnleonard here is my bingAuth.py, i just tested and searches worked. https://drive.google.com/open?id=0B02U8PG-uPGfeFBXYVMtWFRnMWM
if u get any of those server couldnt fill request rerun, this bot needs some reviving

**Comment by FadeVT** [comment]
My thread just got flagged as a duplicate and I was redirected here... so I am here to say none of these fixes worked for my issue.

**Comment by zengfu94** [comment]
@FadeVT whats the traceback for the error? In the other thread yours was the could not find variable t issue, and the above bingAuth.py fixes that.

**Comment by aaronjohnleonard** [comment]
@zengfu94 your bingAuth.py doesn't work for me either.

**Comment by zengfu94** [comment]
What error are you getting @aaronjohnleonard ?

**Comment by FadeVT** [comment]
@zengfu94 

Traceback (most recent call last):
  File "./main.py", line 23, in <module>
    from bingAuth import BingAuth, AuthenticationError
  File "./pkg/bingAuth.py", line 304
    Open with
            ^
SyntaxError: invalid syntax

**Comment by aaronjohnleonard** [comment]
@zengfu94  Before I change anything, I get the "Could not find variable t on Live login page" error. When I make your changes, I get the "The server couldn't fulfill the request" error.

**Comment by zengfu94** [comment]
@FadeVT use the one on the google drive link or make the proper changes, seems like you typed extra text

**Comment by zengfu94** [comment]
@aaronjohnleonard whats the error code, theres always a number after server could not fulfill the request

**Comment by aaronjohnleonard** [comment]
Ahh I see what you're asking. It's 302.

**Comment by zengfu94** [comment]
@aaronjohnleonard set the user agent to a non windows 10 UA

**Comment by FadeVT** [comment]
@zengfu94 I used the one you posted, and that was the traceback.

**Comment by zengfu94** [comment]
mine does not have a line 304(last line 301), open it and remove the extra stuff on that line @FadeVT

**Comment by elisiano** [comment]
Please guys submit PRs instead of sharing the modified file. This way a clone/pull bring everyone on the same page.

**Comment by imckumar** [comment]
I Copied the same file posted by @zengfu94 and getting same 'couldn't fulfill' error:

The server couldn't fulfill the request.
Error code:  302

**Comment by zengfu94** [comment]
@imckumar set the user agent to something other than windows 10

**Comment by kylef000** [comment]
@zengfu94 it works here, I'm making a PR to merge your changes.

**Comment by zengfu94** [comment]
I hard forked this to https://github.com/zengfu94/MicrosoftRewards, I'll be committing there since there is so much broken, outdated and useless code here. Join me if you'd like, exciting updates ahead

**Comment by kylef000** [comment]
Sounds good. Will be happy to contribute as needed.

**Comment by imckumar** [comment]
@zengfu94 i am adding below in config.xml

            <ua_desktop><![CDATA[Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0)]]></ua_desktop>
            <ua_mobile><![CDATA[Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Version/10.0 Mobile/14D27 Safari/602.1]]></ua_mobile>

I am still getting error 302  :( 

below is from bingAuth.py:
# get PPSX parameter
        #ppsxSearch = self.ppsxValue.search(page) 
        #if ppsxSearch == None:
            #raise AuthenticationError("Could not find variable 't' on Live login page")
        #PPSX = ppsxSearch.group(1)

        PPSXs = ["P","Pa","Pas","Pass","Passp","Passpo","Passpor","Passport","PassportR","PassportRN"]
        PPSX = random.choice(PPSXs)

Am i doing something wrong ?

**Comment by rthomp10** [comment]
YES. Love you Zengfu

**Comment by zengfu94** [comment]
@imckumar Trident in the UA search Google for a chrome user agent

**Comment by imckumar** [comment]
@zengfu94 
Sorry, it didn't work with below either:
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by Maledar** [comment]
I've been reading this since it started up, I downloaded zengfu94 file, replaced removed my old one to my desktop to backup just in case, replaced with zengs file and searching running. thanks Zeng

**Comment by zengfu94** [comment]
@Maledar glad I could help!

**Comment by Maledar** [comment]
Just remembered the only thing I've ever changed before this was this issue I had. 
https://github.com/sealemar/BingRewards/issues/250

from user specu

> in pkg/bingFlyoutParser.py for now I changed the line that has SEARCH_AND_EARN_DESCR_RE to say:
SEARCH_AND_EARN_DESCR_RE = re.compile(r".*p to (\d+) points? (?:per day|today), (\d+) points? per search.?")

I'm dont know python, so I dont know if the match is supposed to be partial (to match preceeding promo text) or case insensitive ("Up to" vs "up to"), but it's just the promo description throws off the code that determines search count that needs to be performed.

**Comment by imckumar** [comment]
@Maledar you are lucky then! for me, it's still not working. Not sure what's wrong with my config. 
everything was working till yesterday. I again deleted whole BingRewards-master and copied the one bingAuth.py which @zengfu94  shared, Got 302 error:
The server couldn't fulfill the request.
Error code:  302

I edited config.xml to include user-agent:
   <accounts>
        <account type="Live" disabled="false">
            <login>xxxxx</login>
            <password>xxxxxxx</password>
            <ua_desktop><![CDATA[Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36]]></ua_desktop>
            <ua_mobile><![CDATA[Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.114 Mobile Safari/537.36]]></ua_mobile>
        </account>
    </accounts>

The error still continues :( 

The server couldn't fulfill the request.
Error code:  302

**Comment by Maledar** [comment]
@imckumar 

:( so sorry not sure what you could do aside from delete all, redownload from the github and then only change the file zeng uploaded, and renter your login info. Best of luck to you hope you get it resolved

**Comment by zengfu94** [comment]
@imckumar go in bingFlyoutParser and look for line that says EARN_MORE_CREDITS and change the string following it to "Earn more points" instead of "Earn more credits"

**Comment by imckumar** [comment]
SILVER_STATUS        = (11,   "Silver Status",                     None, False, Action.PASS)
        INVITE_FRIENDS       = (12,   "Invite friends",                    None, False, Action.PASS)
        EARN_MORE_CREDITS    = (13,   "Earn more points",                  None, False, Action.INFORM)


I changed it to Earn more points and it circles back to below output:
retry #2
Live - xxxx@hotmail.com

Live - xxxx@hotmail.com

Points before:      6740
Points after:       6740
Points earned:         0
Lifetime Credits:   6740

--------------------------------------------------------------------------------

**Comment by zengfu94** [comment]
@imckumar can you run it main.py with the -v switch and put output on pastebin or text file

**Comment by imckumar** [comment]
[main.py.output.txt](https://github.com/sealemar/BingRewards/files/1298159/main.py.output.txt)
Please check attached file for output. Below are true at moment:
1) config.xml has user-agent:
<ua_desktop>< ! [CDATA[Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36]]></ua_desktop>
<ua_mobile>< ! [CDATA[Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.114 Mobile Safari/537.36]]></ua_mobile>

2) EARN_MORE_CREDITS    is Earn more points
3) bingAuth.py is copied from what zengfu shared

**Comment by zengfu94** [comment]
@imckumar lol man your searches are already done, it's not gonna search more

**Comment by imckumar** [comment]
@zengfu94  i am so sorry, i am an idiot :( 
Thank you all for checking and spending time in helping.

**Comment by DarkAlexWang** [comment]
@zengfu94 @DARKKRAKEN Hi guys, I updated zengfu94's fix and it works very well. However, it seems like I am not earning any points. I run the program several times, but no luck. I also looked into the search history on bing website, the searched items are not showing in the history. Do you guys have any suggestions? Thanks

**Comment by zengfu94** [comment]
@DarkAlexWang I suggest you try my fork, MS changed some stuff and this one seems to fail at handling some of the cookies.

**Comment by amayer5125** [comment]
@zengfu94 if you open pull requests to improve this project, I would be more than happy to review them.

**Comment by carterschieffer** [comment]
I believe this is happening because the variable "t" is now the variable "r". I've changed my local copy to look for "r" and it's been working. I'll submit a PR.

**Comment by aaronjohnleonard** [comment]
@carterschieffer I think this works for me. I've already manually maxed out my bing searches, so I can't verify 100% that it works, but the output looks much more normal. Thanks!

**Comment by zengfu94** [comment]
If you compare the value in variable r to the one posted as PPSX they are usually not the same @carterschieffer also r does not exist when t exists and vice versa

**Comment by cyclo-techtwister** [comment]
@zengfu94 Thank you that fix worked for myself, now searching and getting points..

**Comment by carterschieffer** [comment]
@zengfu94 The variable "r" and the PPSX value are always the same for me. Are you inspecting in chrome or viewing source? If you view source they likely won't be the same since that's a new page request. I've only been looking at this since yesterday, but I haven't encountered a "t" variable yet.

**Comment by uruloki** [comment]
After a few attempts, the code from @zengfu94 is the code that I can get working. It does not work for me to replace 't' with 'r' per @carterschieffer. Thanks both for looking at this!

**Comment by zengfu94** [comment]
PPSX = 'PassportRN'[:-random.randint(0,9) or None] slightly cleaner version

**Comment by drmaq** [comment]
@cyclo-techtwister @zengfu94  This works thanks

**Comment by specu** [comment]
@zengfu94 what does changing EARN_MORE_CREDITS to "Earn more points" from "Earn more credits" do exactly?

**Comment by zengfu94** [comment]
Kills 302 error, when bot hits that link it screws it up. The thing is no longer called earn more credits, now earn more points. @specu

**Comment by zengfu94** [comment]
302 error I mean cannot use Windows 10 user agents.

**Comment by FadeVT** [comment]
As of this morning, I no longer am experiencing these issues. Did a fresh clone and everything is now working butter smooth again.  (Tried this yesterday and the day before, and it wasn't working. So I am assuming one of the pull requests fixed it.)

**Comment by specu** [comment]
@zengfu94 is Windows 10 = Edge 15.15.15063? it doesnt give me Error 302 but I'll confirm a bit later. Also I dont think there's any benefit over Edge 12, is there?

**Comment by zengfu94** [comment]
It's using a Windows 10 UA without edge in it so it prompts u to use edge == 302. user agents really don't matter, edge 12 vs 15 won't change a thing

**Comment by specu** [comment]
if confirmed, does it then make sense to put in a PR to make it:
EARN_MORE_CREDITS = (13, re.compile("Earn more (?:credits|points)"), None, True, Action.INFORM)
?
@zengfu94 @amayer5125

**Comment by zengfu94** [comment]
You don't even needs the credits part, it's just earn more points.

**Comment by wastingoctober** [comment]
> @zengfu94 I hard forked this to https://github.com/zengfu94/MicrosoftRewards, I'll be committing there since there is so much broken, outdated and useless code here. Join me if you'd like, exciting updates ahead

What happened to your repo? I went to check it out earlier, and it's gone now.
