### ISSUE TITLE
New dashboard page

### ISSUE THREAD

**Issue by baltimoron** [sealemar/BingRewards#303]
A few of my accounts have a new dashboard page, which causes the parser to fail. A vast majority are still on the old one and running fine but I'm assuming a mass changeover is coming. Partial screenshot of the new page attached. I'm working on a new parser for this one but if someone wants to beat me to it feel free.

**Comment by specu** [comment]
dashboard would be at https://account.microsoft.com/rewards/dashboard
do those accounts get redirected to https://account.microsoft.com/rewards/ from the dashboard?

**Comment by baltimoron** [comment]
It's redirecting now.

**Comment by specu** [comment]
I see it. pretty horrible as far as locating information. it's not clear what else I could have done, but daily tally shows I could have made 300+ extra points somewhere. I and probably others are cheering for you @baltimoron  :)

**Comment by baltimoron** [comment]
Got something written up that I think will work, just waiting for one of my accounts with the new dashboard to roll around for testing.

**Comment by specu** [comment]
I got 1 account migrated as well, if you'd like me to give it a test as well.

**Comment by cmdrshepard84** [comment]
I have a migrated account as well, willing to give it a try to see if it fixes the problem I'm running into.

**Comment by baltimoron** [comment]
It looks like it's correctly identifying and determining the type for all rewards (it's also grabbing the sneak peak rewards but I should be able to figure out how to exclude those). Searches are working fine. The big issue I'm seeing is that the hits are being hit but not resulting in any points, which might be a tough one to solve. I've gotta run but will upload something tonight, should be good to get some more eyes on this to see if we can figure out the hit issue.

**Comment by rustyshackleford2017** [comment]
@baltimoron Thank you so much for your work on this! We're depending on you! If I understand correctly you got the code to handle the page correctly but although searches run they don't register points onto the account? Regardless I want to thank you for all the work you have done in the past and now because I use this script a lot and I don't know enough to fix issues myself.

**Comment by baltimoron** [comment]
Ok I've got something uploaded to my fork: https://github.com/baltimoron/BingRewards. Searches work correctly and return points but hits do not. I also made a change to filter out the "sneak peek" rewards.

**Comment by specu** [comment]
@baltimoron running your fork i get an error: "'NoneType' object has no attribute 'find'"

**Comment by baltimoron** [comment]
@specu I must have missed something when I copied the changes over, looking into it now.

**Comment by specu** [comment]
I wish it gave us filename and line number that threw the exception

**Comment by rustyshackleford2017** [comment]
@baltimoron Just tried your fork and it works like a charm for the searches! Thank you so so much! You're a genious!

**Comment by specu** [comment]
@baltimoron  Now I get : 
'NoneType' object has no attribute 'find_all'
Perhaps I should try to export your fork and overwrite current stable file structure.

**Comment by specu** [comment]
@baltimoron : update: that was my mistake, apologies. Runs fine now - thank you!

**Comment by SeeMoreCode** [comment]
**@specu** & **@baltimoron** 
Have you guys had any issues running this new version with a config file containing accounts on the new UI and old UI?

I have 2 accounts one updated to the new UI and one not. When I run this version (V 3.16.13.16.1) I get the this error for the account still on the old UI.

![error](https://user-images.githubusercontent.com/33968533/33882276-93565714-df05-11e7-8cb0-aac3b0ae6b8f.png)

 If I remove the old UI account from the config the script works fine. Thoughts?

**Comment by specu** [comment]
@SeeMoreCode I put @baltimoron code in a new folder and I'm running it only for accounts that are converted. They'll all inevitably be converted eventually (maybe 1/1?). this is all still in testing phase.

**Comment by SeeMoreCode** [comment]
@specu 
Thanks for the quick reply its reassuring that it is working as designed.

**Comment by baltimoron** [comment]
I'll test it more with the old dashboard later today. The version I run at home is very customized so there might still be a couple of issues with the stock version that I wouldn't see.

**Comment by cmdrshepard84** [comment]
Searches all completed and points were earned. The extra clicks stuff doesn't seem to work, but that's fine. At the very least the account is able to earn points again, and that's progress!

Result 1/9:
-----------
name        : Shop & earn
url         : https://www.bing.com/explore/rewards-shop-and-earn?FORM=ML13VU&CREA=ML13VU&wt.mc_id=ML13VU&rnoreward=1
progressCur : 0
progressMax : 20000
progress %  : 0.00%
description : Earn 1 point per $1 spent at the Microsoft Store. Terms apply.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

Result 2/9:
-----------
name        : 12 Days of Deals
url         : https://www.microsoft.com/en-us/store/b/12-days-of-deals?OCID=12Days-Q2-17-en-us-promo-1
progressCur : 0
progressMax : 1
progress %  : 0.00%
description : Get that perfect deal every day at Microsoft Store.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

Result 3/9:
-----------
name        : Holiday villains
url         : https://www.bing.com/search?q=bing+holiday+quiz&FORM=ML16DO&OCID=ML16DO&wt.mc_id=ML16DO
progressCur : 0
progressMax : 10
progress %  : 0.00%
description : Who are these well-known Scrooges?
   Error    :   true
   Message  : Expected to earn 10 points, but earned 0 points. Check error_20171212-090654.307608.html for further information
   Action   : hit

Result 4/9:
-----------
name        : Your gift ideas
url         : https://www.msn.com/en-us/lifestyle/shopping?ocid=MICROSOFTREWARDS
progressCur : 0
progressMax : 10
progress %  : 0.00%
description : Find the most popular holiday gifts & great ideas for your entire list.
   Error    :   true
   Message  : Expected to earn 10 points, but earned 0 points. Check error_20171212-090655.348715.html for further information
   Action   : hit

Result 5/9:
-----------
name        : The Gifted
url         : https://www.microsoft.com/en-us/store/tv/the-gifted/8d6kgwxjfhtl?OCID=Gifted-Q2-17-en-us-promo-1
progressCur : 0
progressMax : 1
progress %  : 0.00%
description : Purchase season 1 of The Gifted and earn 2,000 points for a limited time.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

**Comment by baltimoron** [comment]
Another code merging issue. It's fixed for real this time, will work with both the new and old dashboard.

**Comment by CSJudd** [comment]
Fresh download just now, old dashboard on the testing account, and getting "'NoneType' object has no attribute 'find_all'" error right after it attempts the login (on screen output)

**Comment by specu** [comment]
@CSJudd i was getting that when i accidentally was running old (current stable) code, not balitimoron's patch.

**Comment by CSJudd** [comment]
to make sure, I am running from a folder with just this patched code, no existing .pyc files, etc. - stable/current code has been zipped up and copied off so I can test "clean"... only thing the "same" is the config/xml - one account in it

**Comment by baltimoron** [comment]
I just did a fresh pull of the latest version and it ran fine.

**Comment by imckumar** [comment]
Hi @baltimoron , i am still on older dashboard , I downloaded latest from https://github.com/baltimoron/BingRewards, searches are running fine but no points earned. do you know what could be issue ?

**Comment by baltimoron** [comment]
@imckumar are you running on a residential IP or a data center IP? The latter are IP banned so your searches will run but not be counted.

**Comment by imckumar** [comment]
@baltimoron , Thanks for your reply. i am running these on GCP and AWS cloud machines :( 
So i guess, i will have to run on my local machine then.

**Comment by baltimoron** [comment]
@CSJudd try logging in manually. Sometimes that error is due to account lockout.

**Comment by CSJudd** [comment]
@baltimoron - logged into account manually and even did a quiz, ran this a few times trying "well maybe I need the uagent, etc" and then would go back to browser/rewards dashboard and nothing incremented.  did a few pc searches on it, got points, etc so I know it's not an account or lockout issue.  stumped...  this is the only script on the machine.

**Comment by baltimoron** [comment]
@CSJudd that's weird. Anyone else having this issue?

**Comment by specu** [comment]
if rewards dont increase when running searches manually then it's definitely not a script's fault. i think i had something like that in the past, i've tried running it manually for a couple of days and then it started working again.

**Comment by specu** [comment]
@baltimoron it would be great if the script also ran the edge bonus searches:
Microsoft Edge bonus
Earn up to 20 points a day, 600 points a month, when you search Bing in Microsoft Edge.
20 of 20 points

**Comment by a1270** [comment]
@specu , why not just set your desktop user-agent string to edge?
> <ua_desktop>![CDATA[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.17025]]</ua_desktop>

I do as much and it works fine.

**Comment by specu** [comment]
@a1270 not always which is my point. I think the script calculates number of desktop searches to run around 150 not 170.

**Comment by baltimoron** [comment]
@specu it's based on the page source. I'd rather not add more logic to that (assuming that page source is't being adjusted for edge). Why not just increase addSearchesDesktop by a few to accommodate?

**Comment by specu** [comment]
will do, thank you :)

**Comment by rustyshackleford2017** [comment]
@baltimoron I have your code that was working perfect for 2 or 3 days but then I got this error today. Some kind of character problem but I am not really sure what exactly:

```
For: Live - myemail@gmail.com

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "Desktop/BingRewards/mainpy", line 282, in <module>
    EventsProcessor.onScriptFailure(config, e)
  File "Desktop/BingRewards/mainpy", line 280, in <module>
    __run(config)
  File "Desktop/BingRewards/mainpy", line 205, in __run
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "Desktop/BingRewards/mainpy", line 167, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "Desktop/BingRewards/mainpy", line 55, in earnRewards
    rewards = bdp.parseDashboardPage(bingRewards.getDashboardPage(), bingCommon.ACCOUNT_URL)
  File "Desktop/BingRewards/pkg/bingDashboardParser.py", line 125, in parseDashboardPage
    validRwd = createRewardNewFormat(page, currentTitle, newRwd)
  File "Desktop/BingRewards/pkg/bingDashboardParser.py", line 361, in createRewardNewFormat
    createReward(newRwd, rewardURL, rewardName, rewardProgressCurrent, rewardProgressMax, rewardDescription)
  File "Desktop/BingRewards/pkg/bingDashboardParser.py", line 292, in createReward
    reward.description = rDesc.strip().encode('latin-1', 'ignore')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 51: ordinal not in range(128)
```
Any idea what this is about?

**Comment by specu** [comment]
will do, thank you :)

**Comment by baltimoron** [comment]
@rustyshackleford2017  it's the dash in the description: "It's Ugly Christmas Sweater Day. Be bold and bright—and keep warm." Anyone know how to handle text encoding stuff like this? It's not something I'm very familiar with.

**Comment by baltimoron** [comment]
@rustyshackleford2017 it should be fixed by the latest commit.

**Comment by rustyshackleford2017** [comment]
Thank you so much I will try it today.

**Comment by SeeMoreCode** [comment]
@baltimoron 

Have you tried using your script with more than 2 accounts? For me it seems that that the logic of the script never attempts to go beyond two accounts listed in the config file.

**Comment by baltimoron** [comment]
@SeeMoreCode I run 4 accounts but have a customized setup, not the base code. I doubt anything that I added would cause this issue, anyone else out there seeing it?

**Comment by rustyshackleford2017** [comment]
@baltimoron Sorry for taking so long to get back. As of this moment I just downloaded the latest commit and I don't get the ascii error anymore but I get:

`2017-12-19 07:54:00.9 - script started
--------------------------------------------------------------------------------


For: Live - myemail@gmail.com

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "Desktop/BingRewards/main.py", line 282, in <module>
    EventsProcessor.onScriptFailure(config, e)
  File "Desktop/BingRewards/main.py", line 280, in <module>
    __run(config)
  File "Desktop/BingRewards/main.py", line 205, in __run
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "Desktop/BingRewards/main.py", line 167, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "Desktop/BingRewards/main.py", line 55, in earnRewards
    rewards = bdp.parseDashboardPage(bingRewards.getDashboardPage(), bingCommon.ACCOUNT_URL)
  File "Desktop/BingRewards/pkg/bingDashboardParser.py", line 114, in parseDashboardPage
    for ddiv in rewardsDashboard.find_all('div', class_='spacer-32-top display-table'):
AttributeError: 'NoneType' object has no attribute 'find_all'`

Some type of table access error I believe.

**Comment by baltimoron** [comment]
Can you make sure your account isn't locked out? Also the previous encoding error was on a daily reward so you wouldn't necessarily see it every day, but I'm pretty sure the latest commit fixed that issue anyway.

**Comment by specu** [comment]
I had the ascii error as well but after git pull it ran fine

**Comment by rustyshackleford2017** [comment]
@baltimoron So sorry for wasting your time on that, when I went to download the newest version I mistakenly got the sealemar one instead of yours. However, I do have a different issue when I run yours:

I just downloaded a fresh copy of your version from https://github.com/baltimoron/BingRewards and the only thing different is the config file which has my personal account info in it. I ran it and I get an error relating to the date:

```
2017-12-19 17:03:51.5 - script started
--------------------------------------------------------------------------------


For: Live - myemail@gmail.com

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "Desktop/BingRewards/main.py", line 282, in <module>
    EventsProcessor.onScriptFailure(config, e)
  File "Desktop/BingRewards/main.py", line 280, in <module>
    __run(config)
  File "Desktop/BingRewards/main.py", line 205, in __run
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "Desktop/BingRewards/main.py", line 167, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "Desktop/BingRewards/main.py", line 55, in earnRewards
    rewards = bdp.parseDashboardPage(bingRewards.getDashboardPage(), bingCommon.ACCOUNT_URL)
  File "Desktop/BingRewards/pkg/bingDashboardParser.py", line 129, in parseDashboardPage
    validRwd = createRewardNewFormat(page, currentTitle, newRwd)
  File "Desktop/BingRewards/pkg/bingDashboardParser.py", line 312, in createRewardNewFormat
    attrDateObj = datetime.strptime(cleanString(current[1]), '%m/%d/%Y')
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%m/%d/%Y'

```

**Comment by baltimoron** [comment]
@rustyshackleford2017 it's probably the same error, but it's trying to handle it through the fail script which isn't working. Make sure that the path to the script is correct and that you have execute permissions on it (chmod a+x <filename>). Can you paste a screenshot of what it looks like when you log in manually? I'm curious as to what the selector looks like. That could be the issue although based on where the crash is occurring it looks like it's already beyond that point.

**Comment by rustyshackleford2017** [comment]
@baltimoron You are right that it is beyond that point because I created an alias email for my MS account and now I can login manually with that different email without it asking me which account I want. However, the script still fails in the same way as with the other email for this same account when I put the alias email in config.xml.

I checked that it had execute permissions and ran chmod a+x on it without errors. However, when I run it I still get the same problem. I am running it directly from the folder it is in so I know I have the path right. It's really weird because the problem is specific to this account. This is my oldest account and the only one that has switched to the new dash so far.

**Comment by rustyshackleford2017** [comment]
I commented out lines 310 - 314 in the bingDashboardParser file and now the script runs the searches but I assume it won't be able to get some/all the click rewards. The section I commented out is the part that checks if the reward is actually a sneak peak for tomorrows' reward:

`if attrType == "daily_set_date" != -1:
                #if this reward is not for today (sneak peek rewards are tomorrow), we don't want it
                attrDateObj = datetime.strptime(cleanString(current[1]), '%m/%d/%Y')
                if not (attrDateObj.year == curDate.year and attrDateObj.month == curDate.month and attrDateObj.day == curDate.day):
                    isValid = False`

I also tried leaving the above code in there but putting print(current[1]) instead of the attrDateObj line and it prints:
`12/21/2017
12/21/2017
12/21/2017
12/22/2017
12/22/2017
12/22/2017`
Which looks like the same format as %m/%d/%Y.

**Comment by baltimoron** [comment]
Yeah it's weird that it's crashing on the date since those formats look correct. I also can't reproduce it, my converted accounts are running fine. What will happen with that check commented out is that you will hit all the sneak peek rewards in addition to today's rewards, which is something that could potentially give away the fact that you're botting, although I doubt MS checks for it.

**Comment by rustyshackleford2017** [comment]
@baltimoron I'm not sure if this means anything but I put an extra " - " in the strptime '%m/%d/%Y' line like `attrDateObj = datetime.strptime(cleanString(current[1]), '%m-/%d/%Y')` and it returned:
`ValueError: time data '12/21/2017' does not match format '%m-/%d/%Y` which is weird because it actually has the right date there whereas with the correct format it says time data ' ' without a date. Do you know why it might return null like that? I looked around and the only thing I could find was in regards to locale and I don't think that is the issue since my other accounts run fine.

**Comment by specu** [comment]
I get the same thing now:
time data '' does not match format '%m/%d/%Y'

**Comment by baltimoron** [comment]
Weird, I'm still not seeing it. What OS and user agent are you guys running with?

**Comment by specu** [comment]
@baltimoron windows 10 edge 15

**Comment by specu** [comment]
@baltimoron windows 10 edge 15

**Comment by rustyshackleford2017** [comment]
@baltimoron I'm on a Ubuntu 16.04 machine. I am not sure what my user agent is, I never changed whatever the default is in the script.

**Comment by specu** [comment]
@baltimoron I think the date is empty string for reward with description "3 answers = 30 points. How fast can you rack 'em up?", which is a reward that shows after 'Buy Middle-earth™'. 
I encapsulated it around re before trying to convert just to ignore it rather than error out:
```
                if re.match( "[0-9]*\/[0-9]*\/[0-9]*", cleanString(current[1]) ):
                    attrDateObj = datetime.strptime(cleanString(current[1]), '%m/%d/%Y')
                    if not (attrDateObj.year == curDate.year and attrDateObj.month == curDate.month and attrDateObj.day == curDate.day):
                        isValid = False
                else:
                    isValid = False
```

**Comment by specu** [comment]
@baltimoron confirmed it's the Lightspeed Quiz:
"daily_set_date":""

**Comment by baltimoron** [comment]
Super weird that I'm not seeing it but I'll go ahead and a check for null and empty strings for all the fields since that should be done anyway.

**Comment by FadeVT** [comment]
Im getting this on both the Sealemar and the Baltimoron fork...

`xxx@xxx:~/NewBingRewards$ ./main.py
2017-12-21 19:11:36.2 - script started
--------------------------------------------------------------------------------


For: Live - xxx@gmail.com

--------------------------------------------------------------------------------
/bin/sh: 1: /home/BingRewards/bin/BingRewards/notify/onScriptFailure.sh: not found
xxx@xxx:~/NewBingRewards$`

**Comment by baltimoron** [comment]
Latest commit added checks for empty strings for fields that have logic performed on them (dates + urls). For other fields empty strings are fine (although not ideal). I didn't add a null check because the fields are part of a key-value pair so they shouldn't ever be null.

**Comment by baltimoron** [comment]
@FadeVT can you make sure your config file has the right path to the onScriptFailure script? It looks like it isn't finding it.

**Comment by FadeVT** [comment]
I've never set it up. It has always worked in the past and still works for every other account I have. Would that actually stop it from running searches all of a sudden?

**Comment by rustyshackleford2017** [comment]
@baltimoron Do those null checks still prevent the bot from trying the sneak peaks from the next day? Wondering if the bot detection issue was solved by that fix. I just got the latest version and it works great though, thank you so much @baltimoron and @specu for your attention to this issue.

**Comment by baltimoron** [comment]
@FadeVT That script is for error reporting, if it executes properly then it's much easier to see what error is causing that account to fail.

@rustyshackleford2017 If the date is still there it will check, if not then it will assume the reward is for today. Based on @specu's post it looks like the reward with the missing date was a quiz, so it wouldn't be hit regardless. If they start leaving the date field blank for all rewards I'll see if there's some other way to identify the sneak peeks. I think the image in the top right corner of the box is different so I could potentially filter them out based on that.

**Comment by puternutt** [comment]
@baltimoron  I received the error at the top of the issue, so after reading through this, I downloaded and ran your script, received this error: 
IOError: CRC check failed 0xedcb5ddaL != 0xddfe4e8cL

**Comment by specu** [comment]
@puternutt it happens sometimes when the http response compression fails at some point. it will work if your script retries.
