### ISSUE TITLE
Script won't start

### ISSUE THREAD

**Issue by Horvath-N** [sealemar/BingRewards#327]
I'm really new to all this, but when I try to run the script I get this message.
(I just started yesterday, and it worked just fine then.)

2018-01-25 10:57:44.0 - script started
--------------------------------------------------------------------------------

For: Live - xxx@live.com

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "main.py", line 282, in <module>
    EventsProcessor.onScriptFailure(config, e)
  File "main.py", line 280, in <module>
    __run(config)
  File "main.py", line 205, in __run
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "main.py", line 167, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "main.py", line 55, in earnRewards
    rewards = bdp.parseDashboardPage(bingRewards.getDashboardPage(), bingCommon.ACCOUNT_URL)
  File "pkg/bingDashboardParser.py", line 171, in parseDashboardPage
    hits = checkForHit(currAction, rewardProgressCurrent, rewardProgressMax, links[i])
  File "pkg/bingDashboardParser.py", line 221, in checkForHit
    rewardProgressMax = int(currAction.get_text().split(' ')[0])
ValueError: invalid literal for int() with base 10: 'DONATE'

**Comment by specu** [comment]
duplicated of issue #326 #
