### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by puternutt** [sealemar/BingRewards#339]
Good evening all, so I have this error now and have had it for a few weeks, it was different when the dashboard updated, all of my accounts verified they are on the new dashboard and able to login and click daily's etc. So checked that. I downloaded and replaced the entire directory of files for the latest version about 3 days ago, haven't run the script since until again tonight to make sure the error was still there. I see many of you are stumped and having trouble with this and trying to get it going again. I do as many of us non-programmers do appreciate your hard work. 

I was wondering if this error below means anything to anyone? Anything I can do to fix it? I mean any searching is better than none. So any help or correcting of files would be appreciated. 

**Progress_ counter : Traceback (most recent call last):
  File "...\BingRewards-master\main.py", line 282, in <module> EventsProcessor.onScriptFailure(config, e)
  File "...\BingRewards-master\main.py", line 280, in <module> __run(config)
  File "...\BingRewards-master\main.py", line 205, in __run __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "...\BingRewards-master\main.py", line 167, in __processAccount earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "...\BingRewards-master\main.py", line 55, in earnRewards rewards = bdp.parseDashboardPage(bingRewards.getDashboardPage(), bingCommon.ACCOUNT_URL)
  File "...\BingRewards-master\pkg\bingDashboardParser.py", line 114, in parseDashboardPage
    for ddiv in rewardsDashboard.find_all('div', class_='spacer-32-top display-table'):
AttributeError: 'NoneType' object has no attribute 'find_all'**

**Comment by S3phi40T** [comment]
Are you sure you have accounts added properly?
In <accounts> make sure you have login@domain.com 
Make sure password is not too complex (some special characters make script crash)
In <onComplete> make sure accounts have "Live_" prefix added. Live_account@domain.com

**Comment by specu** [comment]
same as #310 ? are you running the latest version? it seems like your version doesnt handle the new dashboard.

**Comment by specu** [comment]
@puternutt are you still having this issue? pls close if solved.

**Comment by puternutt** [comment]
1) what is the latest version? according to my version.txt I'm on Current version 3.16.1
2) what does the config.xml file supposed to look like? in a post a while back the events was setup for linux, I dont' use linux for my script, I use windows with a python program install that it calls up in the command path. But based on what @S3phi40T is saying with the Live_ that only shows up in the Events section, so I'll pull the code from the .dist file and copy it back in, update the notify paths to match my directory structure and add the emails in there and see what happens.

**Comment by S3phi40T** [comment]
@puternutt please use @baltimoron fork - it's the latest one:
https://github.com/baltimoron/BingRewards

**Comment by puternutt** [comment]
Thanks @S3phi40T 

before baltimoron's fork I updated the events and received this error:

Traceback (most recent call last):
  File "\BingRewards-master\main.py", line 271, in <module>
    config.parseFromFile(configFile)
  File "\BingRewards-master\pkg\config.py", line 518, in parseFromFile
    tree = et.parse(configFile)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 115, column 6

what does this mean?

**Comment by puternutt** [comment]
ok, updated all files to @baltimoron 's latest and re-ran it, same error as the traceback above

**Comment by puternutt** [comment]
This appears to be related to a print on line 271 call

    print "%s - script started" % helpers.getLoggingTime()
    print "-" * 80
    print

    helpers.createResultsDir(__file__)

    config = Config()

    try:
        config.parseFromFile(configFile)
    except IOError, e:
        print "IOError: %s" % e
        sys.exit(2)
    except ConfigError, e:
        print "ConfigError: %s" % e
        sys.exit(2)

    try:
        __run(config)
    except BaseException, e:
        if verbose:
            traceback.print_exc()
        EventsProcessor.onScriptFailure(config, e)

**Comment by puternutt** [comment]
So first, I put in the <events> section and placed the emails in according to the examples. I then ran the script and received the above error. After I saw the line 271, I went to the config file again and commented out this:
	

After this, the same error popped up, but now on line 280 which begins with

try:
 config.parseFromFile (configFile)

**Comment by baltimoron** [comment]
I think it's trying to run the old dashboard parser, so the if statement to go to the new one isn't catching. They might be messing with the dashboard code but only testing it out on certain accounts. I should have some time today to look into this.

**Comment by baltimoron** [comment]
@puternutt I'm only seeing this on banned accounts.

**Comment by puternutt** [comment]
@baltimoron none of the accounts are banned for me, I've logged into each one of them and didn't receive any error, or request to verify anything it took me directly to the account profile page, I then browsed to the rewards page and did some quizzes on each and a few daily's. No changes.

**Comment by puternutt** [comment]
@baltimoron I did another git pull and updated the files, I began to run the script after configuring the config file and I received a this account is banned error, I then logged into each account again and none of them were banned especially the one it stated was. I clicked a few 10 point items and logged out of each, then re-ran the script and the error I get now is this just after the attemtp of the warpspeed reward 9/9

Reward 9/9:
-----------
name        : Warpspeed Quiz
url         : https://www.bing.com/rewards/checkuser?rabruid=0&ru=%2Fsearch%3Fq%3DMarvel+Comics%26rnoreward%3D1%26FORM%3DML12JG%26skipopalnative%3Dtrue%26rqpiodemo%3D1%26filters%3DBTEPOKey%3A%22REWARDSQUIZ_MSR_ThursdayBonusQuiz_20180308%22+BTROID%3A%22Gamification_DailySet_20180308_Child2%22+BTROEC%3A%22Gamification_DailySet_20180308_Child2%22+BTROEC%3A%220%22+BTROMC%3A%2250%22
progressCur : 0
progressMax : 50
progress %  : 0.00%
description : 5 answers = 50 points. Use Bing to get there fast.
hit identifier: Gamification_DailySet_20180308_Child2
hit hash: a75787a1dfdab8c7434ab31f087686cff34beebbed528d9fe89a8f4037aea7ad

Live - bringscript#1Fan@hotmomma.com
**ValueError: unknown url type: /news?q=us+news&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1**

For: Live - bringscript#1Fan@hotmomma.com

--------------------------------------------------------------------------------

But the script does appear to be continuing to run after this error, so I'm going to let the log file build over night and see what it does in the morning.

**Comment by puternutt** [comment]
@baltimoron Thank you, in essence, I finished the script run from last night for all accounts and that same error came up in the same place in all 3 retrys per account, the rest of the daily's didn't give an error. And Result printout kicked out fine, though only one account showed points earned. So I'm Re-Running the script now and I Suspect in a few hours I'll know if it runs the searches for me and if I get any error's I'll post log updates of errors then for both runs for you.

**Comment by puternutt** [comment]
@baltimoron this appears to be a hit and miss, the accounts that don't collect points get the errors, the one to two that does collect points dont' get any errors. So I double checked the accounts and some are at level 1 since the script was down for so long they didn't maintain the level 2 status. But no searches, no daily's nothing on the level 1's I assume they would at least get the searches for level 1. The script is looking at them and attempting, just not producing.
