### ISSUE TITLE
No stacktrace, no points

### ISSUE THREAD

**Issue by NoskcajXela** [sealemar/BingRewards#348]
It seems that I've hit a snag, I've seen only one other instance of an output like this, but no accompanying solution was posted.

This is what the script is printing out when I run:

2018-02-06 20:13:28.1 - script started
--------------------------------------------------------------------------------

For: Live - [my email address]

--------------------------------------------------------------------------------

Full log:
---------
Empty log
onScriptFailure: -mail

I can post my config if needed (and remove important bits)

**Comment by specu** [comment]
could you please pull the latest update from git and try again?

**Comment by NoskcajXela** [comment]
I now receive an stacktrace. The NoType attribute in between the last dashes and full log

Traceback (most recent call last):
  File "./main.py", line 289, in <module>
    __run(config)
  File "./main.py", line 214, in __run
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "./main.py", line 176, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "./main.py", line 56, in earnRewards
    rewards = bdp.parseDashboardPage(bingRewards.getDashboardPage(), bingCommon.ACCOUNT_URL)
  File "./pkg/bingDashboardParser.py", line 142, in parseDashboardPage
    for ddiv in rewardsDashboard.find_all('div', class_='spacer-32-top display-table'):
AttributeError: 'NoneType' object has no attribute 'find_all'

I've tried to check over my config, but I can't find anything

**Comment by specu** [comment]
That's the error people get when the script doesn't support the new dashboard.
does this fork fix it for you?
https://github.com/baltimoron/BingRewards

**Comment by NoskcajXela** [comment]
Hmmm, I have the same output as before

**Comment by S3phi40T** [comment]
@wipedout I'm not sure about Macs, but on Linux I have added "auto update" before script starts so I don't have to check versions , download manually and set up permissions any more.

#!/bin/bash
git -C /home/pi/BingRewards/ pull
/home/pi/BingRewards/main.py
