### ISSUE TITLE
ValueError: unknown url type: /news?...

### ISSUE THREAD

**Issue by shalpape** [sealemar/BingRewards#363]
I have tried the troubleshooting guide and here is what I get:

```bash
$> ./main.py --version
Bing Rewards Automation script: <http://sealemar.blogspot.com/2012/12/bing-rewards-automation.html>
Version: 3.16.1 from November 1, 2017
See 'version.txt' for the list of changes
This code is published under LGPL v3 <http://www.gnu.org/licenses/lgpl-3.0.html>
There is NO WARRANTY, to the extent permitted by law.
Developed by: Sergey Markelov

$> git log -1 --no-color
commit 8a990d41e68e2ba0bbe6afe6f54990e821588ef8
Merge: 0bc9ef6 46110f1
Author: Alex Mayer <amayer5125@gmail.com>
Date:   Tue Feb 13 09:07:39 2018 -0500

    Merge pull request #199 from JustinOhms/master

    Allow main.py to run from alternate directories

$> python --version
Python 2.7.12

$> cat /etc/issue
Ubuntu 16.04.4 LTS \n \l
```

Unfortunately, there is no stack trace.

When running main.py from console I'm getting the same error as in issue #349.

```bash
$> ./main.py
2018-03-27 22:17:16.3 - script started
--------------------------------------------------------------------------------

Live - givenname.surname@outlook.com
ValueError: unknown url type: /news?q=German+news&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1

For: Live - givenname.surname@outlook.com

--------------------------------------------------------------------------------
Live - second.givenname.surname@outlook.com
ValueError: unknown url type: /news?q=German+news&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1

For: Live - second.givenname.surname@outlook.com

--------------------------------------------------------------------------------
Total points earned: 0

2018-03-27 22:17:30.0 - script ended
```

Unlike in issue #349 my accounts are not level 1 but level 2.

I did a fresh clone, installed Beautiful Soup (python-bs4), and run ./main.py.

```bash
$> apt search python-bs4
Sorting... Done
Full Text Search... Done
python-bs4/xenial,now 4.4.1-1 all [installed]
  error-tolerant HTML parser for Python
```

Is it a bug in the code or did I miss something?

My config.xml looks good, I think.

```xml
<?xml version="1.0"?>
<configuration>
    <general
        betweenQueriesInterval="15.0"
        betweenQueriesSalt="12.0"
        betweenAccountsInterval="3"
        betweenAccountsSalt="6"
        openTopLinkRange="5"
        openLinkChance=".7"
        addSearchesDesktop="0"
        addSearchesDesktopSalt="20"
        addSearchesMobile="0"
        addSearchesMobileSalt="20" />
    <accounts>
        <account type="Live" disabled="false">
            <login>givenname.surname@outlook.com</login>
            <password>firstPass</password>
        </account>
        <account type="Live" disabled="false">
            <login>second.givenname.surname@outlook.com</login>
            <password>secondPass</password>
        </account>
    </accounts>
    <queries generator="wikipedia" />
</configuration>
```

**Comment by BenoitThibias** [comment]
I have the exact same message : 
`./main.py --version
Bing Rewards Automation script: <http://sealemar.blogspot.com/2012/12/bing-rewards-automation.html>
Version: 3.16.1 from November 1, 2017`

`python --version
Python 2.7.6`

`Ubuntu 14.04.5 LTS \n \l`

`python-bs4/trusty,now 4.2.1-1ubuntu2 all [installed]
  error-tolerant HTML parser for Python`

And error : 
`Live - email_address@hotmail.com
ValueError: unknown url type: /news?q=French+actualités&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1

For: Live - email_address@hotmail.com`

The actual email address used have an `_` in it,

**Comment by specu** [comment]
i dont see that. did either of you clicked one of those postsed non-US quizes and changed the locale of your rewards account?

**Comment by shalpape** [comment]
Sure, my locale is Germany.

**Comment by specu** [comment]
I dont know if the script is supposed to work outside US. I saw some patch to make it work in Canada.

**Comment by shalpape** [comment]
Meanwhile I applied my own patch. It's a quick and very dirty solution. Otherwise I would place a pull request.

**Comment by BenoitThibias** [comment]
@shalpape can you share that fix with me ?

**Comment by Mibo5354** [comment]
Can the patch be tweaked to work with Australia as well?
``ValueError: unknown url type: /news?q=australian+news&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1

**Comment by shalpape** [comment]
Sorry for my late reply.
Here is what I did.
I hope it'll be helpful.

```diff
diff --git a/pkg/bingDashboardParser.py b/pkg/bingDashboardParser.py
index 20e5c41..1f52871 100644
--- a/pkg/bingDashboardParser.py
+++ b/pkg/bingDashboardParser.py
@@ -43,8 +43,11 @@ class Reward:
             ISRE        = 3
             ACTION      = 4

-        SEARCH_AND_EARN_DESCR_RE = re.compile(r"[Uu]p to (\d+) points? (?:per day|today), (\d+) points? per search")
-        SEARCH_AND_EARN_DESCR_RE_MOBILE = re.compile(r"(\d+) points per search on Microsoft Edge mobile app or (\d+) points per search on any other mobile browser, for up to (\d+) mobile searches per day")
+        #SEARCH_AND_EARN_DESCR_RE = re.compile(r"[Uu]p to (\d+) points? (?:per day|today), (\d+) points? per search")
+        #SEARCH_AND_EARN_DESCR_RE_MOBILE = re.compile(r"(\d+) points per search on Microsoft Edge mobile app or (\d+) points per search on any other mobile browser, for up to (\d+) mobile searches per day")
+        SEARCH_AND_EARN_DESCR_RE = re.compile(r"bis zu (\d+) Punkte pro Tag, (\d+) Punkte pro Suche auf dem PC")
+        SEARCH_AND_EARN_DESCR_RE_MOBILE = re.compile(r"bis zu (\d+) Punkte pro Tag, (\d+) Punkte pro Suche auf dem Mobiltelefon")
+
         #need to change this to work for hits
         EARN_CREDITS_RE = re.compile("Earn (\d+) credits?")

@@ -54,8 +57,8 @@ class Reward:
         RE_EARN_CREDITS_PASS = (1,    EARN_CREDITS_RE,
                             "Get the best of Bing by signing in with Facebook.", True,  Action.PASS)
         RE_EARN_CREDITS      = (2,    EARN_CREDITS_RE,                     None, True,  Action.HIT)
-        SEARCH_MOBILE        = (3,    "Mobile search",                     None, False, Action.SEARCH)
-        SEARCH_PC            = (4,    "PC search",                         None, False, Action.SEARCH)
+        SEARCH_MOBILE        = (3,    "Mobile Suche",                      None, False, Action.SEARCH)
+        SEARCH_PC            = (4,    "PC-Suche",                          None, False, Action.SEARCH)
         YOUR_GOAL            = (5,    "Your goal",                         None, False, Action.INFORM)
         MAINTAIN_GOLD        = (6,    "Maintain Gold",                     None, False, Action.INFORM)
         REFER_A_FRIEND       = (7,    "Refer-A-Friend",                    None, False, Action.PASS)
diff --git a/pkg/bingRewards.py b/pkg/bingRewards.py
index b0a8d31..bda76c3 100644
--- a/pkg/bingRewards.py
+++ b/pkg/bingRewards.py
@@ -240,9 +240,12 @@ class BingRewards:
             return res

         pointsEarned = self.getRewardsPoints()
-        request = urllib2.Request(url = reward.url, headers = self.httpHeaders)
-        with self.opener.open(request) as response:
-            page = helpers.getResponseBody(response)
+        try:
+            request = urllib2.Request(url = reward.url, headers = self.httpHeaders)
+            with self.opener.open(request) as response:
+                page = helpers.getResponseBody(response)
+        except ValueError:
+            print('Non-accessible URL found in reward destination.')
         pointsEarned = self.getRewardsPoints() - pointsEarned
 # check if we earned any points
         if pointsEarned < 1:
@@ -276,10 +279,10 @@ class BingRewards:

 # find out how many searches need to be performed
         matchesMobile = False
-        matches = bdp.Reward.Type.SEARCH_AND_EARN_DESCR_RE.search(reward.description)
+        matches = bdp.Reward.Type.SEARCH_AND_EARN_DESCR_RE.search(reward.description.replace('\xa0', ' '))
         #Mobile description changed, so check that one too
         if matches is None:
-            matches = bdp.Reward.Type.SEARCH_AND_EARN_DESCR_RE_MOBILE.search(reward.description)
+            matches = bdp.Reward.Type.SEARCH_AND_EARN_DESCR_RE_MOBILE.search(reward.description.replace('\xa0', ' '))
             matchesMobile = True
         if matches is None:
             print "No RegEx matches found for this search and earn"
@@ -296,18 +299,18 @@ class BingRewards:
 # so divide it by points per search (rewardsCount) to get correct search count needed
         searchesCount -= (reward.progressCurrent * rewardCost) / rewardsCount

-        if matchesMobile == True:
-            #new mobile search description gives total search count + points per search for edge/non-edge
-            edgeValue = int(matches.group(1))
-            nonEdgeValue = int(matches.group(2))
-            searchesCount = int(matches.group(3))
-            #apparently ios uses EdgiOS, so we only check the first 3 letters not the full word 'edge'
-            if self.userAgents.mobile.lower().find("edg") != -1:
-                #we are searching on edge so points go to 200
-                searchesCount -= reward.progressCurrent / edgeValue
-            else:
-                #non-edge search so 100 is the max
-                searchesCount -= reward.progressCurrent / nonEdgeValue
+#        if matchesMobile == True:
+#            #new mobile search description gives total search count + points per search for edge/non-edge
+#            edgeValue = int(matches.group(1))
+#            nonEdgeValue = int(matches.group(2))
+#            searchesCount = int(matches.group(3))
+#            #apparently ios uses EdgiOS, so we only check the first 3 letters not the full word 'edge'
+#            if self.userAgents.mobile.lower().find("edg") != -1:
+#                #we are searching on edge so points go to 200
+#                searchesCount -= reward.progressCurrent / edgeValue
+#            else:
+#                #non-edge search so 100 is the max
+#                searchesCount -= reward.progressCurrent / nonEdgeValue

         headers = self.httpHeaders
```

**Comment by BenoitThibias** [comment]
Thanks for your help :) It seems to work better, but I still have an error : 

`Traceback (most recent call last):
  File "./main.py", line 27, in <module>
    from bingRewards import BingRewards
  File "/github/BingRewards_dirty/pkg/bingRewards.py", line 286
    matchesMobile = True
    ^
IndentationError: unexpected indent`

I commented that line, script is running but not working ;) ie : getting no reward.
